CASH_DONATION_TYPE = "CASH"
CHECK_DONATION_TYPE = "CHECK"
CC_DONATION_TYPE = "CC"
ONLINE_DONATION_TYPE = "ONLINE"
INKIND_DONATION_TYPE = "INKIND"
GRANT_DONATION_TYPE = "GRANT"
PLEDGE_DONATION_TYPE = "PLEDGE"
STOCK_DONATION_TYPE = "STOCK"
OTHER_DONATION_TYPE = "OTHER"

DONATION_TYPES = [
    (CASH_DONATION_TYPE, "Cash"),
    (CHECK_DONATION_TYPE, "Check"),
    (CC_DONATION_TYPE, "Credit Card"),
    (ONLINE_DONATION_TYPE, "Online"),
    (INKIND_DONATION_TYPE, "In -Kind"),
    (GRANT_DONATION_TYPE, "Grant"),
    (PLEDGE_DONATION_TYPE, "Pledge"),
    (STOCK_DONATION_TYPE, "Stock"),
    (OTHER_DONATION_TYPE, "Other"),
]