. .bashrc

export PIP_DOWNLOAD_CACHE=/tmp/pip
export DJANGO_SETTINGS_MODULE=settings
export PYTHONPATH=$PYTHONPATH:~/sites/digitalmycelium.com/checkouts/digitalmycelium.com
export EDITOR=nano

. sites/digitalmycelium.com/bin/activate

cd ~/sites/digitalmycelium.com/


alias chk='cd /home/mycelium/sites/digitalmycelium.com/checkouts/digitalmycelium.com'
alias run='cd /home/mycelium/sites/digitalmycelium.com/run'
