STATUS_FREE_TRIAL = 0
STATUS_EXPIRED = 10
STATUS_ACTIVE = 20
STATUS_ACTIVE_BILLING_ISSUE = 30
STATUS_DEACTIVATED = 40
STATUS_CANCELLED = 50

ACCOUNT_STATII = [
    (STATUS_FREE_TRIAL, "Free Trial"),
    (STATUS_EXPIRED, "Expired"), # Free trial expired
    (STATUS_ACTIVE, "Active"),
    (STATUS_ACTIVE_BILLING_ISSUE, "Active, Billing Issue"), # Was paid, billing failed.
    (STATUS_DEACTIVATED, "On Hold"),  # no way to get to this currently
    (STATUS_CANCELLED, "Cancelled"),   
]

MONTHLY_PLAN_NAME = "monthly"
YEARLY_PLAN_NAME = "yearly"

FREE_TRIAL_STATII = [
    ACCOUNT_STATII[0][0],
]

HAS_A_SUBSCRIPTION_STATII = [
    ACCOUNT_STATII[2][0],
    ACCOUNT_STATII[3][0],
]
HAD_A_SUBSCRIPTION_STATII = HAS_A_SUBSCRIPTION_STATII + [
    ACCOUNT_STATII[4][0],
    ACCOUNT_STATII[5][0],
]

CANCELLED_SUBSCRIPTION_STATII = [
    ACCOUNT_STATII[5][0],
]
ACTIVE_SUBSCRIPTION_STATII = [
    ACCOUNT_STATII[0][0],
    ACCOUNT_STATII[1][0],
    ACCOUNT_STATII[2][0],
    ACCOUNT_STATII[3][0],
]
BILLING_PROBLEM_STATII = [
    ACCOUNT_STATII[1][0],
    ACCOUNT_STATII[3][0],
]

ACCESS_LEVEL_STANDARD      = 0
ACCESS_LEVEL_ALPHA         = 10
ACCESS_LEVEL_BETA          = 20
ACCESS_LEVEL_BLEEDING_EDGE = 30

FEATURE_ACCESS_STATII = [
    (ACCESS_LEVEL_STANDARD,  "Standard"),
    (ACCESS_LEVEL_ALPHA, "Beta"),
    (ACCESS_LEVEL_BETA, "Alpha"),
    (ACCESS_LEVEL_BLEEDING_EDGE, "Bleeding Edge"),
]