STATUS_FREE_TRIAL = 0
STATUS_EXPIRED = 10
STATUS_ACTIVE = 20
STATUS_ACTIVE_BILLING_ISSUE = 30
STATUS_DEACTIVATED = 40
STATUS_CANCELLED = 50

ACCOUNT_STATII = [
    (STATUS_FREE_TRIAL, "Free Trial"),
    (STATUS_EXPIRED, "Expired"), # Free trial expired
    (STATUS_ACTIVE, "Active"),
    (STATUS_ACTIVE_BILLING_ISSUE, "Active, Billing Issue"), # Was paid, billing failed.
    (STATUS_DEACTIVATED, "On Hold"),
    (STATUS_CANCELLED, "Cancelled"),   
]

MONTHLY_PLAN_NAME = "monthly"
YEARLY_PLAN_NAME = "yearly"

FREE_TRIAL_STATII = [
    STATUS_FREE_TRIAL,
]

HAS_A_SUBSCRIPTION_STATII = [
    STATUS_ACTIVE,
    STATUS_ACTIVE_BILLING_ISSUE,
]
HAD_A_SUBSCRIPTION_STATII = HAS_A_SUBSCRIPTION_STATII + [
    STATUS_DEACTIVATED,
    STATUS_CANCELLED,
]

CANCELLED_SUBSCRIPTION_STATII = [
    STATUS_CANCELLED,
]
DEACTIVATED_SUBSCRIPTION_STATII = [
    STATUS_DEACTIVATED
]

ACTIVE_SUBSCRIPTION_STATII = [
    STATUS_FREE_TRIAL,
    STATUS_EXPIRED,
    STATUS_ACTIVE,
    STATUS_ACTIVE_BILLING_ISSUE,
]
BILLING_PROBLEM_STATII = [
    STATUS_EXPIRED,
    STATUS_ACTIVE_BILLING_ISSUE,
]

ACCESS_LEVEL_STANDARD      = 0
ACCESS_LEVEL_ALPHA         = 10
ACCESS_LEVEL_BETA          = 20
ACCESS_LEVEL_BLEEDING_EDGE = 30

FEATURE_ACCESS_STATII = [
    (ACCESS_LEVEL_STANDARD,  "Standard"),
    (ACCESS_LEVEL_ALPHA, "Beta"),
    (ACCESS_LEVEL_BETA, "Alpha"),
    (ACCESS_LEVEL_BLEEDING_EDGE, "Bleeding Edge"),
]