#!/bin/sh

# Where to chdir at start.
CELERYD_CHDIR="/var/www/mycelium.git/mycelium"

CELERYD_OPTS="celeryd -B -E"

DJANGO_SETTINGS_MODULE="settings"

CELERYD="/root/.virtualenvs/mycelium/bin/python2.6 $CELERYD_CHDIR/manage.py"

VIRTUALENV="/root/.virtualenvs/mycelium"

CELERYD_USER="root"